# Constants
from pygame.font import FontType

WIDTH, HEIGHT = 800, 600
FPS = 60
PLAYER_SPEED = 5
PLAYER_ACELERATION = 100
PLAYER_DEACELERATION = PLAYER_ACELERATION * 1/10
ROTATION_SPEED = 200
INVENCIBLETIME = 3
SAWSPEED = 10

# Proyectile
PROJECTILE_SPEED = 10
PROJECTILE_COOLDOWN = 0.5
CHANGEWEAPONCOOLDOWN = 0.2
PROJECTILE_VOLUME = 0.2

# Sounds Paths
MUSIC = "../res/Sounds/music.mp3"
BASIC_PROJECTILE_SOUND = "../res/Sounds/laser.mp3"
NET_PROJECTILE_SOUND = "../res/Sounds/rope.mp3"
SAW_PROJECTILE_SOUND = "../res/Sounds/saw.mp3"

# Enemy
ROTATION_SPEED = 200
ENEMY_SPEED = 3
RANDCOOLDOWN = 1
RANDMULTILIER = 3
KILLEDROTATIONSPEED = 1
KILLANIMATIONTIME = 3
ENEMYSHOOTCOOLDOWN = 0.5
ENEMYSHOOTRAND = 50
RUBBISHSPEEDMUL = .2

# Enemy killbar
KILLBARWIDTH = 60
KILLBARHEIGHT = 5
AFTERKILLTIME = 20

# Debug
SHOWHITBOX = False

# Colors
WHITE = (255, 255, 255)
GREY = (150, 150, 150)
BLUE = (0, 0, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLACK = (0, 0, 0)


# UI
UIPOSITION = 9/10
